blog_homepage:
     path:     /
     defaults: { _controller: MorozBlogBundle:Post:index, _locale:ua }
     requirements:
            _locale: ua|ru|en
blog_index:
    path:     /
    path:     /{_locale}/
    defaults: { _controller: MorozBlogBundle:Post:index }
    requirements:
                _locale: ua|ru|en
#----post
blog_post_new:
    path:     /{_locale}/post/new
    defaults: { _controller: MorozBlogBundle:Post:new}
    requirements:
                _locale: ua|ru|en
blog_post_show:
    path:     /{_locale}/post/{postId}
    defaults: { _controller: MorozBlogBundle:Post:show}
    requirements:
         _method: GET
         _locale: ua|ru|en
blog_post_del:
    path:     /{_locale}/post/{postId}/del
    defaults: { _controller: MorozBlogBundle:Post:del}
    requirements:
         _method: GET
         _locale: ua|ru|en
blog_post_edit:
    path:     /{_locale}/post/{postId}/edit
    defaults: { _controller: MorozBlogBundle:Post:edit }
    methods: [GET, POST]
    requirements:
          _locale: ua|ru|en

#----comment
blog_comment_add:
        path:     /{_locale}/post/{postId}/comment/add
        defaults: { _controller: MorozBlogBundle:Comment:add }
        requirements:
              _locale: ua|ru|en
