blog_homepage:
    path:     /
    defaults: { _controller: MorozBlogBundle:Post:index }

blog_post_show:
    path:     /post/{id}
    defaults: { _controller: MorozBlogBundle:Post:show}
    requirements:
         _method: GET

blog_post_new:
    path:     /post/new
    defaults: { _controller: MorozBlogBundle:Post:new}

blog_post_edit:
    path:     /post/{postId}/edit
    defaults: { _controller: MorozBlogBundle:Post:edit }
    methods: [GET, POST]

