blog_homepage:
    path:     /
    defaults: { _controller: MorozBlogBundle:Post:index }
#----post
blog_post_new:
    path:     /post/new
    defaults: { _controller: MorozBlogBundle:Post:new}

blog_post_show:
    path:     /post/{postId}
    defaults: { _controller: MorozBlogBundle:Post:show}
    requirements:
         _method: GET
blog_post_del:
    path:     /post/{postId}/del
    defaults: { _controller: MorozBlogBundle:Post:del}
    requirements:
         _method: GET
blog_post_edit:
    path:     /post/{postId}/edit
    defaults: { _controller: MorozBlogBundle:Post:edit }
    methods: [GET, POST]
#----comment
blog_comment_add:
        path:     /post/{postId}/comment/add
        defaults: { _controller: MorozBlogBundle:Comment:add }
