parameters:
#    moroz_blog.example.class: Moroz\BlogBundle\Example

services:
#    moroz_blog.example:
#        class: %moroz_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
