Moroz\BlogBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: Moroz\BlogBundle\Entity\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        author:
            type: string
            length: '100'
        comment:
            type: string
            length: '255'
        createdAt:
            type: datetime
        postId:
            type: integer
            column: post_id
    lifecycleCallbacks: {  }
